### ISSUE TITLE
3-phase Induction Motor 

### ISSUE THREAD

**Issue by piyushraw** [RaghavJit/BootCampGNE#11]

**Comment by piyushraw** [comment]
Procedure for the 3- phase Induction Motor

**Step 1:  Make connections as per the instructions given below:
i.	(1-4), (2-5), (3-6)
ii.	(7-10), (8-11)
iii.	(7-12), (13-14)
iv.	(8-15), (9-16) 
Note: Click on the label to delete the connection for the corresponding node.
(a)	Now, Check the connections by clicking on the ‘CHECK’ button.
(b)	If the connections are ‘Invalid connections’ Click on the corresponding label to remove the connection.
(c)	And if the connections are ‘Right Connections’ then follow the below steps.
Step 2: Turn on the MCB 
Step 3: Now, Click on the ‘ADD’ button to add the readings to the observation table.
Step 4: Vary the w1 and w2
Step 5: Now, Click on the ‘ADD’ button to add the readings to the observation table.
Step 6: Repeat steps 4 and 5 until we take the 6 readings in the observation table.
Step 7: Click on the ‘PLOT’ button to plot the graph.
Step 8: Click on the ‘PRINT’ button to takeout the print of the webpage.
STEP 9: Click on the ‘RESET’ button to reload the webpage.**

**Comment by RaghavJit** [comment]
issue resolved in latest commit
