### ISSUE TITLE
Add this code to the Calculation Section for 2 wattmeter method.

### ISSUE THREAD

**Issue by piyushraw** [RaghavJit/BootCampGNE#7]
In the calculation section, all the things will be done manually -::

**User will add the values manually to each text box from the observation table 
and calculate it with the help of Calculate button .**

                                                           //  Html code 

                   <input style="width:70px;" type="button" onclick="multiplyStar()" value = Calculate id="verify1">

                <input style="width: 70px;" type="button" onclick="multiplyDelta()" value="Calculate" id="verify2">

                                                     // Code for the Calculation section //

   function multiplyStar() {

    var num1 = 1.732;
    var num2 = document.getElementById('VLStar').value;
    var num3 = document.getElementById('ILStar').value;
    var num4 = document.getElementById('cosStar').value;
    
    var myResult = num1 * num2 *num3 * num4 ;
    
    document.getElementById('powStar').value= myResult.toFixed(2);
        
    
    }

    function multiplyDelta() {
                                 
       var num1 =  1.732;

       var num2 = document.getElementById('VLDelta').value;
       var num3 = document.getElementById('ILDelta').value;
       var num4 = document.getElementById('cosDelta').value;

       var myResult = num1 * num2 * num3 * num4 ;

       document.getElementById('powDelta').value = myResult.toFixed(2);

    }

**Comment by RaghavJit** [comment]
1.  Made changes to the calculations tab.
2.  Fixed the problem with nodes.
